/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CollectorsRouteImport } from './routes/collectors'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as HishobRouteImport } from './routes/hishob'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PautiRouteImport } from './routes/pauti'
import { Route as PautisRouteImport } from './routes/pautis'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HouseholdsIndexRouteImport } from './routes/households.index'
import { Route as HouseholdsIdRouteImport } from './routes/households.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorsRoute = CollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const HishobRoute = HishobRouteImport.update({
  id: '/hishob',
  path: '/hishob',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PautiRoute = PautiRouteImport.update({
  id: '/pauti',
  path: '/pauti',
  getParentRoute: () => rootRouteImport,
} as any)
const PautisRoute = PautisRouteImport.update({
  id: '/pautis',
  path: '/pautis',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIndexRoute = HouseholdsIndexRouteImport.update({
  id: '/households/',
  path: '/households/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIdRoute = HouseholdsIdRouteImport.update({
  id: '/households/$id',
  path: '/households/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/collectors': typeof CollectorsRoute
  '/expenses': typeof ExpensesRoute
  '/hishob': typeof HishobRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pauti': typeof PautiRoute
  '/pautis': typeof PautisRoute
  '/settings': typeof SettingsRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/households/': typeof HouseholdsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/collectors': typeof CollectorsRoute
  '/expenses': typeof ExpensesRoute
  '/hishob': typeof HishobRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pauti': typeof PautiRoute
  '/pautis': typeof PautisRoute
  '/settings': typeof SettingsRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/households': typeof HouseholdsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/collectors': typeof CollectorsRoute
  '/expenses': typeof ExpensesRoute
  '/hishob': typeof HishobRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pauti': typeof PautiRoute
  '/pautis': typeof PautisRoute
  '/settings': typeof SettingsRoute
  '/households/$id': typeof HouseholdsIdRoute
  '/households/': typeof HouseholdsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/collectors'
    | '/expenses'
    | '/hishob'
    | '/login'
    | '/notifications'
    | '/pauti'
    | '/pautis'
    | '/settings'
    | '/households/$id'
    | '/households/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/collectors'
    | '/expenses'
    | '/hishob'
    | '/login'
    | '/notifications'
    | '/pauti'
    | '/pautis'
    | '/settings'
    | '/households/$id'
    | '/households'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/collectors'
    | '/expenses'
    | '/hishob'
    | '/login'
    | '/notifications'
    | '/pauti'
    | '/pautis'
    | '/settings'
    | '/households/$id'
    | '/households/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  CollectorsRoute: typeof CollectorsRoute
  ExpensesRoute: typeof ExpensesRoute
  HishobRoute: typeof HishobRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PautiRoute: typeof PautiRoute
  PautisRoute: typeof PautisRoute
  SettingsRoute: typeof SettingsRoute
  HouseholdsIdRoute: typeof HouseholdsIdRoute
  HouseholdsIndexRoute: typeof HouseholdsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collectors': {
      id: '/collectors'
      path: '/collectors'
      fullPath: '/collectors'
      preLoaderRoute: typeof CollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hishob': {
      id: '/hishob'
      path: '/hishob'
      fullPath: '/hishob'
      preLoaderRoute: typeof HishobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pauti': {
      id: '/pauti'
      path: '/pauti'
      fullPath: '/pauti'
      preLoaderRoute: typeof PautiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pautis': {
      id: '/pautis'
      path: '/pautis'
      fullPath: '/pautis'
      preLoaderRoute: typeof PautisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/': {
      id: '/households/'
      path: '/households'
      fullPath: '/households/'
      preLoaderRoute: typeof HouseholdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/$id': {
      id: '/households/$id'
      path: '/households/$id'
      fullPath: '/households/$id'
      preLoaderRoute: typeof HouseholdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  CollectorsRoute: CollectorsRoute,
  ExpensesRoute: ExpensesRoute,
  HishobRoute: HishobRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PautiRoute: PautiRoute,
  PautisRoute: PautisRoute,
  SettingsRoute: SettingsRoute,
  HouseholdsIdRoute: HouseholdsIdRoute,
  HouseholdsIndexRoute: HouseholdsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
